package lab1proyectotransversal.vistas;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import lab1proyectotransversal.accesoADatos.InscripcionData;
import lab1proyectotransversal.accesoADatos.MateriaData;
import lab1proyectotransversal.entidades.Alumno;
import lab1proyectotransversal.entidades.Materia;

/**
 *
 * @author Grupo-3
 */
public class ConsultaAlumnosPorMateria extends javax.swing.JInternalFrame {

    private final DefaultTableModel dtm;
    private final MateriaData materiaData;
    private final InscripcionData inscripcionData;
    private List<Materia> listaMaterias = null;

    /**
     * Creates new form ConsultaAlumnosMateria
     */
    public ConsultaAlumnosPorMateria(MateriaData materiaData, InscripcionData inscripcionData) {
        initComponents();
        this.dtm = (DefaultTableModel) alumnosTable.getModel();
        this.materiaData = materiaData;
        this.inscripcionData = inscripcionData;
    }

    private void actualizarElementosComboBox() {
        materiaSeleccionCB.removeAllItems();
        listaMaterias = materiaData.listarMaterias();
        for (Materia materia : listaMaterias) {
            materiaSeleccionCB.addItem(materia.getNombre());
        }
        materiaSeleccionCB.setSelectedIndex(-1);
    }

    private void actualizarAlumnosTable() {
        // Este metodo esta sujeto al tipo de lista (OJO)
        Materia materiaSeleccionada = listaMaterias.get(materiaSeleccionCB.getSelectedIndex());
        List<Alumno> listaAlumnos = inscripcionData.obtenerAlumnoXMateria(materiaSeleccionada.getIdMateria());

        dtm.setRowCount(0);
        for (Alumno alumno : listaAlumnos) {
            dtm.addRow(new Object[]{alumno.getIdAlumno(), alumno.getDni(), alumno.getApellido(), alumno.getNombre()});
        }
        System.out.println("actualizo tabla");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        materiaSeleccionLabel = new javax.swing.JLabel();
        materiaSeleccionCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        alumnosTable = new javax.swing.JTable();
        salirButton = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Alumnos por Materia");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Listado de Alumnos por Materia");

        materiaSeleccionLabel.setText("Materia Seleccionada:");

        materiaSeleccionCB.setSelectedIndex(-1);
        materiaSeleccionCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaSeleccionCBActionPerformed(evt);
            }
        });

        alumnosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI", "Apellido", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(alumnosTable);

        salirButton.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(materiaSeleccionLabel)
                        .addGap(18, 18, 18)
                        .addComponent(materiaSeleccionCB, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(salirButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materiaSeleccionLabel)
                    .addComponent(materiaSeleccionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(salirButton)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        materiaSeleccionCB.setSelectedIndex(-1);
        dtm.setRowCount(0);
    }//GEN-LAST:event_formComponentShown

    private void materiaSeleccionCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiaSeleccionCBActionPerformed
        if (materiaSeleccionCB.getSelectedIndex() == -1) {
            actualizarElementosComboBox();
        } else {
            actualizarAlumnosTable();
        }
    }//GEN-LAST:event_materiaSeleccionCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable alumnosTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> materiaSeleccionCB;
    private javax.swing.JLabel materiaSeleccionLabel;
    private javax.swing.JButton salirButton;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
