package lab1proyectotransversal.vistas;

import javax.swing.JOptionPane;
import lab1proyectotransversal.accesoADatos.MateriaData;
import lab1proyectotransversal.entidades.Materia;

/**
 *
 * @author Grupo-3
 */
public class GestionMateria extends javax.swing.JInternalFrame {

    MateriaData materiaData;

    /**
     * Creates new form GestionMaterias
     */
    public GestionMateria(MateriaData materiaData) {
        initComponents();
        this.materiaData = materiaData;
    }
    
    private void limpiarCampos(){
        codigoTextField.setText("");
        nombreTextField.setText("");
        anioTextField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        codigoLabel = new javax.swing.JLabel();
        codigoTextField = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        anioLabel = new javax.swing.JLabel();
        anioTextField = new javax.swing.JTextField();
        estadoLabel = new javax.swing.JLabel();
        estadoRadioButton = new javax.swing.JRadioButton();
        nuevoButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        guardarButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        buscarButton = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Materias");

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Materia");
        titulo.setToolTipText("");

        codigoLabel.setText("Codigo:");

        nombreLabel.setText("Nombre:");

        anioLabel.setText("Año:");

        estadoLabel.setText("Estado:");

        estadoRadioButton.setSelected(true);
        estadoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoRadioButtonActionPerformed(evt);
            }
        });

        nuevoButton.setText("Nuevo");
        nuevoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoLabel)
                            .addComponent(nombreLabel)
                            .addComponent(anioLabel)
                            .addComponent(estadoLabel))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codigoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(estadoRadioButton)
                            .addComponent(nombreTextField)
                            .addComponent(anioTextField))
                        .addGap(18, 18, 18)
                        .addComponent(buscarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nuevoButton)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarButton)
                        .addGap(18, 18, 18)
                        .addComponent(guardarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(salirButton)))
                .addGap(24, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLabel)
                    .addComponent(codigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anioLabel)
                    .addComponent(anioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoLabel)
                    .addComponent(estadoRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoButton)
                    .addComponent(eliminarButton)
                    .addComponent(guardarButton)
                    .addComponent(salirButton))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // TODO add your handling code here:
        int idMateria = 0;
        
        try{
            idMateria = Integer.parseInt(codigoTextField.getText());
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El codigo debe ser un numero entero sin decimales", "Error", JOptionPane.ERROR_MESSAGE);
        }
        //buscar materia
        Materia materia=materiaData.buscarMateria(idMateria);
        if(materia == null){
            nombreTextField.setText("");
            anioTextField.setText("");
            JOptionPane.showMessageDialog(this, "No se ha encontrado la materia", "Información", JOptionPane.INFORMATION_MESSAGE);
        }else{
            nombreTextField.setText(materia.getNombre());
            anioTextField.setText(materia.getAnio()+"");
            estadoRadioButton.setSelected(materia.isEstado());
        }
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void nuevoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoButtonActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_nuevoButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        // TODO add your handling code here:
        int idMateria;
        try{
            idMateria=Integer.parseInt(codigoTextField.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "La materia debe ser un numero entero sin decimales", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Materia materia=materiaData.buscarMateria(idMateria);
        if (materia != null) {
            if(materiaData.eliminarMateria(materia.getIdMateria())){
                materia=null;
                limpiarCampos();
                JOptionPane.showMessageDialog(this, "materia eliminada", "Información", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo eliminar la materia", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "No hay materia con este ID", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        // TODO add your handling code here:
        
        int codigo=Integer.parseInt(codigoTextField.getText());
        String nombre=nombreTextField.getText();
        int anio=Integer.parseInt(anioTextField.getText());
        boolean estado=estadoRadioButton.isSelected();
        System.out.println(estado);
        
        
        //validar el id materia
        int idMateria;
        try{
            idMateria=Integer.parseInt(codigoTextField.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "La materia debe ser un numero entero sin decimales", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //buscar materia
        Materia materia=materiaData.buscarMateria(idMateria);
        
        //guardar sql
        boolean result=false;
        
        if(materia==null){
            materia=new Materia(codigo, nombre, anio, estado);
            result=materiaData.guardarMateria(materia);
        }else {
            materia.setIdMateria(idMateria);
            materia.setNombre(nombre);
            materia.setAnio(anio);
            materia.setEstado(estado);
            result=materiaData.modificarMateria(materia);
        }
        //mostrar sql
        if (result) {
            JOptionPane.showMessageDialog(this, "Materia guardada", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se puede guardar la materia", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_salirButtonActionPerformed

    private void estadoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoRadioButtonActionPerformed
        // TODO add your handling code here:
        estadoRadioButton.setSelected(isIcon);
    }//GEN-LAST:event_estadoRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anioLabel;
    private javax.swing.JTextField anioTextField;
    private javax.swing.JButton buscarButton;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoTextField;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JRadioButton estadoRadioButton;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JButton nuevoButton;
    private javax.swing.JButton salirButton;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
